mono: none
dist: xenial
addons:
 snaps:
 - name: dotnet-sdk
   confinement: classic
   channel: latest/beta
sudo: required
language: csharp
git:
 depth: 5
script:
 - sudo snap alias dotnet-sdk.dotnet dotnet
 - sudo snap list --all
 - dotnet --version
 - dotnet build ImageCA
 - dotnet restore
